# Generated by Django 5.1.5 on 2025-01-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('risk', models.CharField(choices=[('I', 'I'), ('IIA', 'IIA'), ('IIB', 'IIB'), ('III', 'III')], max_length=10)),
                ('location', models.CharField(choices=[('Área A', 'Área A'), ('Área B', 'Área B'), ('Área C', 'Área C')], max_length=100)),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Fuera de servicio', 'Fuera de servicio')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
