# Generated by Django 5.1.5 on 2025-01-25 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_card_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='posts.card')),
            ],
        ),
    ]
