# Generated by Django 5.1.5 on 2025-01-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_intervention'),
    ]

    operations = [
    ]
