# Generated by Django 5.1.5 on 2025-01-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_set_default_intervention_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='intervention',
            old_name='responsible_person',
            new_name='responsible',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='description',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='maintenance_type',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='start_time',
        ),
        migrations.AddField(
            model_name='intervention',
            name='intervention_type',
            field=models.CharField(choices=[('preventivo', 'Mantenimiento Preventivo'), ('correctivo', 'Mantenimiento Correctivo'), ('calibracion', 'Calibración')], default='preventivo', max_length=20),
        ),
    ]
