# Generated by Django 5.1.5 on 2025-01-26 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='posts.card'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='posts.card'),
        ),
    ]
