# Generated by Django 5.1.5 on 2025-01-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_cronograma_intervencion_remove_schedule_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronograma',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cronograma',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='intervencion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='intervencion',
            name='tipo',
        ),
        migrations.AddField(
            model_name='cronograma',
            name='nombre_evento',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intervencion',
            name='tipo_intervencion',
            field=models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo'), ('Calibración', 'Calibración')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intervencion',
            name='responsable',
            field=models.CharField(max_length=255),
        ),
    ]
