# Generated by Django 5.1.5 on 2025-01-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_cronograma_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroIntervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_intervencion', models.CharField(choices=[('preventivo', 'Mantenimiento Preventivo'), ('correctivo', 'Mantenimiento Correctivo'), ('calibracion', 'Calibración')], max_length=50)),
                ('fecha', models.DateField()),
                ('responsable', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Intervencion',
        ),
        migrations.RemoveField(
            model_name='cronograma',
            name='nombre_evento',
        ),
        migrations.AddField(
            model_name='cronograma',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
