# Generated by Django 5.1.5 on 2025-01-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_registrointervencion_delete_intervencion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_intervencion', models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo'), ('Calibración', 'Calibración')], max_length=50)),
                ('fecha', models.DateField()),
                ('responsable', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=255)),
                ('schedule_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='RegistroIntervencion',
        ),
        migrations.RemoveField(
            model_name='cronograma',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='cronograma',
            name='nombre_evento',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
