# Generated by Django 5.1.5 on 2025-01-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_intervencion_maintenancedata_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaintenanceData',
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='nombre_evento',
            field=models.CharField(max_length=255),
        ),
    ]
