# Generated by Django 5.1.5 on 2025-01-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_delete_maintenancedata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('tipo_intervencion', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Cronograma',
        ),
        migrations.DeleteModel(
            name='Intervencion',
        ),
    ]
