# Generated by Django 5.1.5 on 2025-01-27 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_maintenancecard_delete_cronograma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancecard',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_cards', to='posts.card'),
        ),
    ]
