# Generated by Django 5.1.5 on 2025-01-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_cronograma_intervencion_delete_maintenancecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Correctiva', 'Correctiva'), ('Preventiva', 'Preventiva'), ('Calibración', 'Calibración')], max_length=20)),
                ('date', models.DateField()),
                ('responsible', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cronograma',
        ),
        migrations.DeleteModel(
            name='Intervencion',
        ),
    ]
