# Generated by Django 5.1.5 on 2025-01-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_intervention_schedule_delete_cronograma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Correctiva', 'Correctiva'), ('Preventiva', 'Preventiva'), ('Calibración', 'Calibración')], max_length=20)),
                ('fecha', models.DateField()),
                ('responsable', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Intervention',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
