# Generated by Django 5.1.5 on 2025-02-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_cronograma_intervencion_delete_intervention_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('cronograma', 'Cronograma'), ('intervencion', 'Intervención')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cronograma',
        ),
        migrations.DeleteModel(
            name='Intervencion',
        ),
    ]
