# Generated by Django 5.1.5 on 2025-02-09 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_maintenanceentry_delete_cronograma_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaintenanceEntry',
        ),
    ]
