# Generated by Django 5.1.5 on 2025-02-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_delete_maintenanceentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroIntervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(choices=[('Correctiva', 'Correctiva'), ('Preventiva', 'Preventiva'), ('Calibración', 'Calibración')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('responsable', models.CharField(max_length=100)),
            ],
        ),
    ]
