# Generated by Django 5.1.5 on 2025-02-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_cronograma_registrointervencion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cronograma',
        ),
        migrations.DeleteModel(
            name='RegistroIntervencion',
        ),
    ]
