# Generated by Django 5.1.5 on 2025-02-10 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_delete_cronograma_delete_registrointervencion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas', to='posts.card')),
            ],
        ),
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('responsable', models.CharField(max_length=255)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervenciones', to='posts.card')),
            ],
        ),
    ]
