# Generated by Django 5.1.5 on 2025-02-10 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_cronograma_intervencion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronograma',
            old_name='fecha',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='cronograma',
            old_name='titulo',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronograma', to='posts.card'),
        ),
        migrations.CreateModel(
            name='RegistroIntervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('correctiva', 'Correctiva'), ('preventiva', 'Preventiva'), ('calibracion', 'Calibración')], max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('responsible', models.CharField(max_length=255)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervenciones', to='posts.card')),
            ],
        ),
        migrations.DeleteModel(
            name='Intervencion',
        ),
    ]
