# Generated by Django 5.1.5 on 2025-04-24 16:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_rename_fecha_cronograma_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='location',
        ),
        migrations.RemoveField(
            model_name='card',
            name='risk',
        ),
        migrations.AddField(
            model_name='card',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='series',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
