# Generated by Django 5.1.5 on 2025-07-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_remove_card_location_remove_card_risk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
