# Generated by Django 5.1.5 on 2025-07-26 04:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_card_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='created_at',
        ),
        migrations.CreateModel(
            name='EventHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('document_added', 'Documento agregado'), ('document_removed', 'Documento eliminado'), ('activity_completed', 'Actividad completada'), ('activity_pending', 'Actividad pendiente'), ('intervention_created', 'Intervención creada'), ('status_changed', 'Cambio de estado')], max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_history', to='posts.card')),
            ],
        ),
    ]
