# Generated by Django 5.1.5 on 2025-07-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_remove_card_created_at_eventhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventhistory',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='deleted_documents/'),
        ),
    ]
