# Generated by Django 5.1.5 on 2025-07-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_eventhistory_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
