# Generated by Django 5.1.5 on 2025-07-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_document_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
