# Generated by Django 5.1.5 on 2025-07-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_card_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventhistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='eventhistory',
            name='event_type',
            field=models.CharField(choices=[('document_added', 'Documento agregado'), ('document_removed', 'Documento eliminado'), ('activity_completed', 'Actividad completada'), ('activity_pending', 'Actividad pendiente'), ('intervention_created', 'Intervención creada'), ('status_changed', 'Cambio de estado'), ('card_created', 'Tarjeta Creada'), ('card_updated', 'Tarjeta Actualizada'), ('card_deleted', 'Tarjeta Eliminada'), ('card_restored', 'Tarjeta Restaurada')], max_length=50),
        ),
        migrations.AlterModelTable(
            name='eventhistory',
            table='event_history',
        ),
    ]
