# Generated by Django 5.1.5 on 2025-07-27 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_alter_eventhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventhistory',
            options={},
        ),
        migrations.AlterModelTable(
            name='eventhistory',
            table=None,
        ),
    ]
