# Generated by Django 5.1.5 on 2025-09-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_alter_eventhistory_options_alter_eventhistory_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='risk',
            field=models.CharField(blank=True, choices=[('I', 'I'), ('IIA', 'IIA'), ('IIB', 'IIB'), ('III', 'III')], max_length=10, null=True),
        ),
    ]
